interval: 300
one_shot: false

github:
  token: "GITHUB_TOKEN"
  repos:
    - "usuario/repositorio"

gitlab:
  token: "GITLAB_TOKEN"
  projects:
    - "12345678"

notifications:
  slack:
    webhook: "https://hooks.slack.com/services/..."
  discord:
    webhook: "https://discord.com/api/webhooks/..."
  email:
    from: "you@example.com"
    to: "alert@example.com"
    smtp_server: "smtp.example.com"
    port: 465
    password: "senha_super_segura"
